export const expenseTypes = [
  { label: "Office Supplies-Expense" },
  { label: "Travel Expense-Expense" },
  { label: "IT and Internet Expenses-Expense" },
  { label: "Rent Expense-Expense" },
  { label: "Meals and Entertainment-Expense" },
  { label: "Other Expenses-Expense" },
  { label: "Parking-Expense" },
  { label: "Advertising/Promotional-Expense" },
  { label: "Bank charges-Expense" },
  { label: "Computer Hardware Maintenance Exp-Expense" },
  { label: "Computer Hire Charges-Expense" },
  { label: "Conveyance Allowance-Expense" },
  { label: "Corporate and Promotional Gifts-Expense" },
  { label: "Donations-Expense" },
  { label: "Electricity-Expense" },
  { label: "Employment Benifit Expenses-Expense" },
  { label: "Food and Refreshment Expenses-Expense" },
  { label: "Housekeeping Charges-Expense" },
  { label: "Income Tax-Expense" },
  { label: "Insurance Expense-Expense" },
  { label: "Loan-Expense" },
  { label: "Medical Allowance-Expense" },
  { label: "Office Equipment-Expense" },
  { label: "Office Maintenance Expenses-Expense" },
  { label: "Phone Reimbursment-Expense" },
  { label: "Pooja Expenses-Expense" },
  { label: "Postage and Delivery-Expense" },
  { label: "Printing and Stationary-Expense" },
  { label: "Professional Charges-Expense" },
  { label: "Professional Fees-Expense" },
  { label: "Office Rent@ I Sprout-Expense" },
  { label: "Rent @ Bangalore-Expense" },
  { label: "Rent @ L & T-Expense" },
  { label: "Repair and maintenance-Expense" },
  { label: "Telephone and Internet Expense-Expense" },
  { label: "Travel Allowance-Expense" },
  { label: "Computers & Laptops-Fixed Asset" },
  { label: "Mobile Phones-Fixed Asset" },
  { label: "Vehicles-Fixed Asset" },
  { label: "Venkat Chitturi Loan-Long Term Liability" },
  { label: "Medical Insurance for Employees-Other Current Asset" },
  { label: "Esi Payable-Other Current Liability" },
  { label: "Income tax payable-Other Current Liability" },
  { label: "Professional Tax Payable-Other Current Liability" },
  { label: "Salaries Payable-Other Current Liability" },
  { label: "GST Payable-Other Current Liability" },
  { label: "Accidental Death Benefit for Employees-Other Expense" },
  { label: "Interest on ICICI Bank Loan-Other Expense" },
  { label: "Interest on TDS-Other Expense" },
  { label: "Miscellaneous Expense-Other Expense" },
  { label: "Other-Other" },
];
