export const expenseTypes = [
  "Office Supplies-Expense",
  "Travel Expense-Expense",
  "IT and Internet Expenses-Expense",
  "Rent Expense-Expense",
  "Meals and Entertainment-Expense",
  "Other Expenses-Expense",
  "Parking-Expense",
  "Advertising/Promotional-Expense",
  "Bank charges-Expense",
  "Computer Hardware Maintenance Exp-Expense",
  "Computer Hire Charges-Expense",
  "Conveyance Allowance-Expense",
  "Corporate and Promotional Gifts-Expense",
  "Donations-Expense",
  "Electricity-Expense",
  "Employment Benifit Expenses-Expense",
  "Food and Refreshment Expenses-Expense",
  "Housekeeping Charges-Expense",
  "Income Tax-Expense",
  "Insurance Expense-Expense",
  "Loan-Expense",
  "Medical Allowance-Expense",
  "Office Equipment-Expense",
  "Office Maintenance Expenses-Expense",
  "Phone Reimbursment-Expense",
  "Pooja Expenses-Expense",
  "Postage and Delivery-Expense",
  "Printing and Stationary-Expense",
  "Professional Charges-Expense",
  "Professional Fees-Expense",
  "Office Rent@ I Sprout-Expense",
  "Rent @ Bangalore-Expense",
  "Rent @ L & T-Expense",
  "Repair and maintenance-Expense",
  "Telephone and Internet Expense-Expense",
  "Travel Allowance-Expense",
  "Computers & Laptops-Fixed Asset",
  "Mobile Phones-Fixed Asset",
  "Vehicles-Fixed Asset",
  "Venkat Chitturi Loan-Long Term Liability",
  "Medical Insurance for Employees-Other Current Asset",
  "Esi Payable-Other Current Liability",
  "Income tax payable-Other Current Liability",
  "Professional Tax Payable-Other Current Liability",
  "Salaries Payable-Other Current Liability",
  "GST Payable-Other Current Liability",
  "Accidental Death Benefit for Employees-Other Expense",
  "Interest on ICICI Bank Loan-Other Expense",
  "Interest on TDS-Other Expense",
  "Miscellaneous Expense-Other Expense",
  "Other-Other",
];
